remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

logo: assets/logo-deci.webp
description: Repositorio de contenidos para el Diplomado en Ciencia de Datos de la Divisi贸n de Educaci贸n Continua e Innovaci贸n de la Escuela Nacional de Estudios Superiores (UNAM), Unidad Le贸n.